import assert from 'assert'
assert(typeof eval === 'undefined', 'eval')
assert(typeof Function === 'undefined', 'Function')
assert(typeof AsyncFunction === 'undefined', 'AsyncFunction')
assert(typeof Atomics === 'undefined', 'Atomics')
assert(typeof WebAssembly === 'undefined', 'WebAssembly')
assert(typeof Worker === 'undefined', 'Worker')
assert(typeof __dirname === 'undefined', '__dirname')
assert(typeof __filename === 'undefined', '__filename')
assert(typeof MessageChannel === 'undefined', 'MessageChannel')
